export const SELECT_DATASET = 'SELECT_DATASET';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const SELECT_ITEM = 'SELECT_ITEM';

export const OPEN_ADD_FORM = 'OPEN_ADD_FORM';
export const CHANGE_INPUT_FIELD = 'CHANGE_INPUT_FIELD';
export const ADD_ITEM = 'ADD_ITEM';

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const START_SEARCH = 'START_SEARCH';

export const SORT_DATA = 'SORT_DATA';
